### ISSUE TITLE
Y-axis range should allow asymmetry

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/plotter#16]
X-axis is allowed to be asymmetrical but Y-axis currently is forced to be. Problematic for certain factors like Abf1 and FoxA1 that are deeply asymmetrical across the y-axis

<img width="229" alt="image" src="https://user-images.githubusercontent.com/18726510/228883579-94feb93b-6be5-4c82-bfeb-f5f838590a5a.png">

**Comment by jcha40** [comment]
Added this in the dev branch, it's a pretty large change so I might need to test a bit more.
