### ISSUE TITLE
Auto-scale is overly precise

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/plotter#18]
Autoscaling the y-axis provides overly precise estimates (74.05364128000001 in this case). Scaling should be slightly more intelligent and precision should be based on the input data. Possibly rounded to the largest sig-fig in the input data?

<img width="642" alt="image" src="https://user-images.githubusercontent.com/18726510/228887089-7432a688-c08d-4eb9-85c4-7c133ef0fd13.png">

**Comment by jcha40** [comment]
Set precision to two significant digits.
