### ISSUE TITLE
Export as SVG fails when label is being edited

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/plotter#19]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/18726510/228947472-a87b6621-7721-494c-a1a1-3154b8fd6e05.png">

**Comment by jcha40** [comment]
I think a decent solution would be to disable the Download as SVG button while the labels are being edited and when you hover over the disabled button it can tell you to press enter on the labels.

**Comment by jcha40** [comment]
Button is now disabled while labels are being edited
